"use client"

import { useState, useCallback, useEffect } from "react"
import {
  DndContext,
  DragOverlay,
  PointerSensor,
  TouchSensor,
  useSensor,
  useSensors,
  type DragStartEvent,
  type DragEndEvent,
} from "@dnd-kit/core"
import { useBuilderStore, generateId, type BuilderElement, type BuilderProject, type ProjectTheme } from "@/lib/builder-store"
import { BuilderSidebar, PALETTE_ITEMS, type PaletteItem } from "./sidebar"
import { BuilderCanvas } from "./canvas"
import { PropertiesPanel } from "./properties-panel"
import { PageFlow } from "./page-flow"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
  DropdownMenuSeparator,
} from "@/components/ui/dropdown-menu"
import {
  Undo2,
  Redo2,
  Monitor,
  Tablet,
  Smartphone,
  GitBranch,
  Plus,
  ChevronDown,
  Pencil,
  Trash2,
  Download,
  Eye,
  Save,
  PanelLeftClose,
  PanelLeftOpen,
  PanelRightClose,
  PanelRightOpen,
  Menu,
  Search,
  Settings2,
  LayoutGrid,
  X,
} from "lucide-react"
import { cn } from "@/lib/utils"
import { useSession } from "next-auth/react"

// ── Mobile palette item categories ────────────────────────────────────────────
const MOBILE_SMALL_ITEMS = PALETTE_ITEMS.filter((i) =>
  ["Typography", "Interactive"].includes(i.category),
)
const MOBILE_MEDIUM_ITEMS = PALETTE_ITEMS.filter((i) =>
  ["Layout", "Media"].includes(i.category),
)
const MOBILE_CIRCLE_ITEMS = PALETTE_ITEMS.filter((i) =>
  ["Structural", "Decorative"].includes(i.category),
)

// ── Types ─────────────────────────────────────────────────────────────────────

type DeviceWidth = "mobile" | "tablet" | "desktop"
type ViewMode = "builder" | "flow"

// ── Code Exporter ─────────────────────────────────────────────────────────────

function projectToTypeScript(project: BuilderProject): string {
  const theme = project.theme
  const pages = project.pageOrder.map((id) => project.pages[id])

  const styleToObj = (style: Record<string, string | undefined>): string => {
    const entries = Object.entries(style)
      .filter(([, v]) => v !== undefined)
      .map(([k, v]) => `    ${k}: "${v}",`)
      .join("\n")
    return entries ? `{\n${entries}\n  }` : "{}"
  }

  const renderElement = (el: BuilderElement, indent = 6): string => {
    const styleObj = Object.entries(el.style)
      .filter(([, v]) => v !== undefined)
      .map(([k, v]) => `${k}: "${v}"`)
      .join(", ")
    const styleAttr = styleObj ? ` style={{ ${styleObj} }}` : ""
    const pad = " ".repeat(indent)

    switch (el.type) {
      case "heading": {
        const tag = `h${el.props.level ?? 2}`
        return `${pad}<${tag}${styleAttr}>${el.props.text ?? "Heading"}</${tag}>`
      }
      case "paragraph":
        return `${pad}<p${styleAttr}>${el.props.text ?? ""}</p>`
      case "button":
        return `${pad}<a href="${el.props.href ?? "#"}"${styleAttr}>${el.props.text ?? "Button"}</a>`
      case "image":
        return `${pad}<img src="${el.props.src ?? ""}" alt="${el.props.alt ?? ""}"${styleAttr} />`
      case "divider":
        return `${pad}<hr${styleAttr} />`
      case "spacer":
        return `${pad}<div${styleAttr} />`
      case "badge":
        return `${pad}<span${styleAttr}>${el.props.text ?? "Badge"}</span>`
      case "input":
        return `${pad}<input type="text" placeholder="${el.props.placeholder ?? "Enter text..."}"${styleAttr} />`
      case "list": {
        const items = (el.props.items as string[] | undefined) ?? ["Item 1", "Item 2"]
        const lis = items.map((item) => `${pad}  <li>${item}</li>`).join("\n")
        return `${pad}<ul${styleAttr}>\n${lis}\n${pad}</ul>`
      }
      default: {
        const children = el.children.map((c) => renderElement(c, indent + 2)).join("\n")
        return `${pad}<div${styleAttr}>${children ? `\n${children}\n${pad}` : ""}</div>`
      }
    }
  }

  const pageComponents = pages
    .map((page) => {
      const compName = page.name.replace(/\s+/g, "") + "Page"
      const body = page.elements.map((el) => renderElement(el)).join("\n")
      return `// Page: ${page.name} — route: ${page.slug}
function ${compName}(): React.JSX.Element {
  return (
    <div>
${body || "      {/* Empty page */}"}
    </div>
  )
}`
    })
    .join("\n\n")

  const routerCases = pages
    .map((page) => {
      const compName = page.name.replace(/\s+/g, "") + "Page"
      return `    case "${page.slug}": return <${compName} />`
    })
    .join("\n")

  const defaultSlug = pages[0]?.slug ?? "/"

  return `// Generated by Sycord Builder — TypeScript / React
// Run: npm create vite@latest my-app -- --template react-ts && cd my-app && npm install
// Replace src/App.tsx with this file.

import React, { useState } from "react"

const theme = {
  primaryColor: "${theme.primaryColor}",
  secondaryColor: "${theme.secondaryColor}",
  fontFamily: "${theme.fontFamily}",
  backgroundColor: "${theme.backgroundColor}",
  textColor: "${theme.textColor}",
  borderRadius: "${theme.borderRadius}",
} as const

${pageComponents}

export default function App(): React.JSX.Element {
  const [route, setRoute] = useState<string>("${defaultSlug}")

  function renderPage(): React.JSX.Element {
    switch (route) {
${routerCases}
      default: return <div style={{ padding: "2rem" }}>404 — Page not found</div>
    }
  }

  return (
    <div
      style={{
        ...${styleToObj({ fontFamily: theme.fontFamily, backgroundColor: theme.backgroundColor, color: theme.textColor })},
        minHeight: "100vh",
      }}
    >
      {/* Simple client-side router — replace with react-router-dom if needed */}
      <nav style={{ display: "none" }}>
        {${JSON.stringify(pages.map((p) => p.slug))}.map((slug) => (
          <button key={slug} onClick={() => setRoute(slug)}>{slug}</button>
        ))}
      </nav>
      {renderPage()}
    </div>
  )
}
`
}

// ── Add Page Dialog ────────────────────────────────────────────────────────────

function AddPageDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { addPage } = useBuilderStore()
  const [name, setName] = useState("")
  const [slug, setSlug] = useState("")

  const handleNameChange = (v: string) => {
    setName(v)
    setSlug("/" + v.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, ""))
  }

  const handleSubmit = () => {
    if (!name.trim()) return
    addPage(name.trim(), slug || `/${name.toLowerCase().replace(/\s+/g, "-")}`)
    setName("")
    setSlug("")
    onClose()
  }

  return (
    <Dialog open={open} onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Add New Page</DialogTitle>
          <DialogDescription>Create a new page in your website project.</DialogDescription>
        </DialogHeader>
        <div className="space-y-4 mt-2">
          <div className="space-y-1.5">
            <Label>Page Name</Label>
            <Input
              value={name}
              onChange={(e) => handleNameChange(e.target.value)}
              placeholder="About Us"
              onKeyDown={(e) => e.key === "Enter" && handleSubmit()}
              autoFocus
            />
          </div>
          <div className="space-y-1.5">
            <Label>URL Slug</Label>
            <Input
              value={slug}
              onChange={(e) => setSlug(e.target.value)}
              placeholder="/about-us"
              className="font-mono text-sm"
            />
          </div>
          <div className="flex justify-end gap-2">
            <Button variant="outline" onClick={onClose}>
              Cancel
            </Button>
            <Button onClick={handleSubmit} disabled={!name.trim()}>
              Add Page
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}

// ── Export Dialog ──────────────────────────────────────────────────────────────

function ExportDialog({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { project } = useBuilderStore()
  const code = projectToTypeScript(project)

  const handleDownload = () => {
    const blob = new Blob([code], { type: "text/plain" })
    const url = URL.createObjectURL(blob)
    const a = document.createElement("a")
    a.href = url
    a.download = `${project.name.toLowerCase().replace(/\s+/g, "-")}-App.tsx`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <Dialog open={open} onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>Export Project — TypeScript</DialogTitle>
          <DialogDescription>
            Download the generated <code>App.tsx</code> for your Vite + React + TypeScript project.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4 mt-2">
          <pre className="bg-muted rounded-lg p-4 text-xs font-mono overflow-auto max-h-64 whitespace-pre-wrap">
            {code}
          </pre>
          <div className="flex justify-end gap-2">
            <Button variant="outline" onClick={onClose}>
              Close
            </Button>
            <Button onClick={handleDownload}>
              <Download className="h-4 w-4 mr-2" />
              Download App.tsx
            </Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}

// ── Theme Panel ───────────────────────────────────────────────────────────────

function ThemePanel({ open, onClose }: { open: boolean; onClose: () => void }) {
  const { project, updateTheme } = useBuilderStore()
  const theme = project.theme

  const update = (key: keyof ProjectTheme, value: string) => updateTheme({ [key]: value })

  return (
    <Dialog open={open} onOpenChange={(o) => !o && onClose()}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>Theme Settings</DialogTitle>
          <DialogDescription>Customize colors and typography for your project.</DialogDescription>
        </DialogHeader>
        <div className="space-y-4 mt-2">
          {(
            [
              { key: "primaryColor", label: "Primary Color", type: "color" },
              { key: "secondaryColor", label: "Secondary Color", type: "color" },
              { key: "backgroundColor", label: "Background", type: "color" },
              { key: "textColor", label: "Text Color", type: "color" },
            ] as { key: keyof ProjectTheme; label: string; type: string }[]
          ).map(({ key, label }) => (
            <div key={key} className="flex items-center justify-between gap-4">
              <Label className="text-sm">{label}</Label>
              <div className="flex items-center gap-2">
                <input
                  type="color"
                  value={(theme[key] as string) ?? "#000000"}
                  onChange={(e) => update(key, e.target.value)}
                  className="h-8 w-12 rounded border border-border cursor-pointer"
                />
                <Input
                  value={(theme[key] as string) ?? ""}
                  onChange={(e) => update(key, e.target.value)}
                  className="h-8 w-28 text-xs font-mono"
                />
              </div>
            </div>
          ))}

          <div className="space-y-1.5">
            <Label className="text-sm">Font Family</Label>
            <Input
              value={theme.fontFamily}
              onChange={(e) => update("fontFamily", e.target.value)}
              placeholder="Inter, sans-serif"
              className="text-sm font-mono"
            />
          </div>

          <div className="space-y-1.5">
            <Label className="text-sm">Border Radius</Label>
            <Input
              value={theme.borderRadius}
              onChange={(e) => update("borderRadius", e.target.value)}
              placeholder="0.5rem"
              className="text-sm font-mono"
            />
          </div>
          <div className="flex justify-end">
            <Button onClick={onClose}>Done</Button>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  )
}

// ── Main DragDropBuilder ───────────────────────────────────────────────────────

interface DragDropBuilderProps {
  projectId: string
  projectName: string
  initialProject?: BuilderProject
  onSave?: (project: BuilderProject) => Promise<void>
  /** When true the component skips its own mobile header so the parent can provide one */
  embedded?: boolean
}

export default function DragDropBuilder({
  projectId,
  projectName,
  initialProject,
  onSave,
  embedded = false,
}: DragDropBuilderProps) {
  const {
    project,
    currentPageId,
    selectedElementId,
    setCurrentPage,
    deletePage,
    addElement,
    undo,
    redo,
    historyIndex,
    history,
    loadProject,
    resetProject,
    setDragging,
  } = useBuilderStore()

  // Initialize project
  // Only reset/load once when projectId changes. loadProject and resetProject are
  // stable Zustand actions; initialProject and projectName are effectively constants
  // per render cycle so excluding them avoids unnecessary re-initialisations.
  useEffect(() => {
    if (initialProject) {
      loadProject(initialProject)
    } else {
      resetProject(projectId, projectName)
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [projectId])

  // Desktop panels
  const [showSidebar, setShowSidebar] = useState(true)
  const [showProperties, setShowProperties] = useState(true)
  const [deviceWidth, setDeviceWidth] = useState<DeviceWidth>("desktop")
  const [viewMode, setViewMode] = useState<ViewMode>("builder")
  const [addPageOpen, setAddPageOpen] = useState(false)
  const [exportOpen, setExportOpen] = useState(false)
  const [themeOpen, setThemeOpen] = useState(false)
  const [isSaving, setIsSaving] = useState(false)
  const [activeDragId, setActiveDragId] = useState<string | null>(null)

  // Mobile-specific state
  const [mobilePanelOpen, setMobilePanelOpen] = useState<"elements" | "properties" | null>(null)
  const [mobileSearch, setMobileSearch] = useState("")
  const { data: session } = useSession()
  const userInitial = ((session?.user?.name ?? session?.user?.email ?? "U")[0] ?? "U").toUpperCase()

  // DnD sensors — support both mouse and touch
  const sensors = useSensors(
    useSensor(PointerSensor, { activationConstraint: { distance: 8 } }),
    useSensor(TouchSensor, { activationConstraint: { delay: 250, tolerance: 5 } }),
  )

  const handleDragStart = useCallback(
    (event: DragStartEvent) => {
      setActiveDragId(String(event.active.id))
      setDragging(true)
    },
    [setDragging],
  )

  const handleDragEnd = useCallback(
    (_event: DragEndEvent) => {
      setActiveDragId(null)
      setDragging(false)
    },
    [setDragging],
  )

  const handleSave = async () => {
    if (!onSave) return
    setIsSaving(true)
    try {
      await onSave(project)
    } finally {
      setIsSaving(false)
    }
  }

  // Mobile tap-to-add: creates and adds an element from the palette
  const addMobileElement = useCallback(
    (item: PaletteItem) => {
      const newEl: BuilderElement = {
        id: generateId(),
        type: item.type,
        props: { ...item.defaultProps },
        style: { ...item.defaultStyle },
        children: [],
      }
      addElement(currentPageId, newEl)
    },
    [addElement, currentPageId],
  )

  // Filtered palette items for mobile search
  const filterItems = (items: PaletteItem[]) =>
    mobileSearch
      ? items.filter((i) => i.label.toLowerCase().includes(mobileSearch.toLowerCase()))
      : items

  const currentPage = project.pages[currentPageId]
  const canUndo = historyIndex > 0
  const canRedo = historyIndex < history.length - 1

  // Shared mobile header component
  const MobileHeader = ({ onMenuClick }: { onMenuClick?: () => void }) => (
    <header className="h-14 shrink-0 flex items-center justify-between px-4 border-b border-border bg-background z-30">
      <button
        onClick={onMenuClick}
        className="p-1.5 rounded-lg hover:bg-accent transition-colors"
        aria-label="Menu"
      >
        <Menu className="h-5 w-5 text-foreground" />
      </button>
      <span className="text-base font-semibold text-foreground truncate px-3 flex-1 min-w-0">
        {projectName}
      </span>
      <div className="h-9 w-9 rounded-full bg-violet-600 flex items-center justify-center text-white font-bold text-sm shrink-0 select-none">
        {userInitial}
      </div>
    </header>
  )

  return (
    <div className={embedded ? "flex flex-col h-full bg-background overflow-hidden" : "flex flex-col h-screen bg-background overflow-hidden"}>

      {/* ══════════════════════════════════════════════════════════════════════
          MOBILE LAYOUT  (hidden on md and above)
      ══════════════════════════════════════════════════════════════════════ */}
      <div className="flex flex-col h-full md:hidden relative overflow-hidden">
        {/* Only show builder's own mobile header when not embedded */}
        {!embedded && <MobileHeader onMenuClick={() => setThemeOpen(true)} />}

        {/* ── Builder mode ─────────────────────────────────────────────────── */}
        {viewMode === "builder" && (
          <DndContext sensors={sensors} onDragStart={handleDragStart} onDragEnd={handleDragEnd}>
            {/* Canvas area */}
            <div className="flex-1 overflow-auto bg-background px-4 pt-4 pb-2">
              <div className="relative">
                {/* The canvas wrapper — grey rounded card */}
                <div className="rounded-2xl overflow-hidden bg-[#575757]">
                  <BuilderCanvas deviceWidth="mobile" />
                </div>
                {/* "+" button on right edge, vertically centred */}
                <button
                  onClick={() => setMobilePanelOpen("elements")}
                  className="absolute right-0 top-1/2 -translate-y-1/2 translate-x-1/3 h-10 w-10 rounded-full bg-[#323232] border-2 border-[#454545] flex items-center justify-center z-10 shadow-lg"
                  aria-label="Add element"
                >
                  <Plus className="h-4 w-4 text-[#999]" />
                </button>
              </div>
            </div>

            {/* Bottom navigation */}
            <div className="shrink-0 px-4 pb-4 bg-background">
              <div className="bg-[#1c1c1e] rounded-3xl flex items-center justify-around px-3 py-3">
                {/* Canvas */}
                <button
                  onClick={() => setMobilePanelOpen(null)}
                  className={cn(
                    "h-14 w-16 rounded-2xl flex items-center justify-center transition-colors",
                    mobilePanelOpen === null ? "bg-[#3a3a3c]" : "bg-[#2c2c2e]",
                  )}
                  aria-label="Canvas"
                >
                  <Pencil className="h-5 w-5 text-[#8e8e93]" />
                </button>
                {/* Elements */}
                <button
                  onClick={() => setMobilePanelOpen("elements")}
                  className={cn(
                    "h-14 w-16 rounded-2xl flex items-center justify-center transition-colors",
                    mobilePanelOpen === "elements" ? "bg-[#3a3a3c]" : "bg-[#2c2c2e]",
                  )}
                  aria-label="Elements"
                >
                  <LayoutGrid className="h-5 w-5 text-[#8e8e93]" />
                </button>
                {/* Flow */}
                <button
                  onClick={() => { setViewMode("flow"); setMobilePanelOpen(null) }}
                  className="h-14 w-16 rounded-2xl bg-[#2c2c2e] flex items-center justify-center"
                  aria-label="Flow"
                >
                  <GitBranch className="h-5 w-5 text-[#8e8e93]" />
                </button>
                {/* Save — visible only when onSave provided */}
                {onSave && (
                  <button
                    onClick={handleSave}
                    disabled={isSaving}
                    className="h-14 w-16 rounded-2xl bg-indigo-600 flex flex-col items-center justify-center gap-0.5 active:scale-95 transition-transform disabled:opacity-50"
                    aria-label="Save"
                  >
                    <Save className="h-5 w-5 text-white" />
                    <span className="text-[8px] text-white font-medium">{isSaving ? "…" : "Save"}</span>
                  </button>
                )}
                {/* Export */}
                <button
                  onClick={() => setExportOpen(true)}
                  className="h-14 w-16 rounded-2xl bg-[#2c2c2e] flex flex-col items-center justify-center gap-0.5 active:scale-95 transition-transform"
                  aria-label="Export"
                >
                  <Download className="h-5 w-5 text-[#8e8e93]" />
                  <span className="text-[8px] text-[#8e8e93] font-medium">Export</span>
                </button>
              </div>
            </div>

            <DragOverlay>
              {activeDragId && (
                <div className="bg-indigo-600 text-white text-xs font-medium px-3 py-1.5 rounded-lg shadow-xl opacity-90 pointer-events-none">
                  Moving element…
                </div>
              )}
            </DragOverlay>
          </DndContext>
        )}

        {/* ── Flow mode ────────────────────────────────────────────────────── */}
        {viewMode === "flow" && (
          <div className="flex flex-col flex-1 overflow-hidden">
            {/* Flow diagram */}
            <div className="flex-1 overflow-hidden">
              <PageFlow />
            </div>

            {/* Page configuration bottom sheet */}
            <div className="shrink-0 bg-[#1c1c1e] rounded-t-[28px] px-5 pt-4 pb-6 shadow-2xl">
              <div className="w-10 h-1 rounded-full bg-[#3a3a3c] mx-auto mb-4" />
              <h3 className="text-center text-base font-bold text-foreground mb-5">
                Page configuration
              </h3>

              {/* select element dropdown */}
              <div className="bg-[#2c2c2e] rounded-2xl px-4 py-3 flex items-center justify-between mb-4 border border-[#3a3a3c]">
                <span className="text-sm font-medium text-foreground">select element</span>
                <ChevronDown className="h-4 w-4 text-foreground" />
              </div>

              {/* Input fields placeholder group */}
              <div className="bg-[#2c2c2e] rounded-2xl px-4 py-3 mb-4 space-y-3 border border-[#3a3a3c]">
                <div className="h-8 rounded-xl bg-[#3a3a3c] w-2/3" />
                <div className="h-8 rounded-xl bg-[#3a3a3c] w-2/3" />
              </div>

              {/* Redirect labels */}
              <div className="space-y-3 px-1">
                <p className="text-sm font-semibold text-foreground">redirect when clicked</p>
                <p className="text-sm font-semibold text-foreground">redirect if</p>
              </div>
            </div>
          </div>
        )}

        {/* ── Mobile Element Palette overlay ───────────────────────────────── */}
        {mobilePanelOpen === "elements" && (
          <div className="absolute inset-0 z-50 bg-background flex flex-col">
            {!embedded && <MobileHeader onMenuClick={() => setMobilePanelOpen(null)} />}
            {embedded && (
              <div className="h-12 shrink-0 flex items-center px-4 border-b border-border">
                <button
                  onClick={() => setMobilePanelOpen(null)}
                  className="p-1.5 rounded-lg hover:bg-accent transition-colors"
                  aria-label="Close"
                >
                  <X className="h-5 w-5 text-foreground" />
                </button>
                <span className="text-sm font-semibold ml-2">Add Element</span>
              </div>
            )}

            {/* Search bar */}
            <div className="px-4 pt-4 pb-3 shrink-0">
              <div className="h-12 rounded-2xl bg-[#2c2c2e] flex items-center px-4 gap-3">
                <Search className="h-4 w-4 text-[#8e8e93] shrink-0" />
                <input
                  className="flex-1 bg-transparent text-sm text-foreground placeholder:text-[#8e8e93] outline-none"
                  placeholder="Search elements…"
                  value={mobileSearch}
                  onChange={(e) => setMobileSearch(e.target.value)}
                />
                {mobileSearch && (
                  <button onClick={() => setMobileSearch("")} className="shrink-0">
                    <X className="h-4 w-4 text-[#8e8e93]" />
                  </button>
                )}
              </div>
            </div>

            {/* Scrollable element grid */}
            <div className="flex-1 overflow-y-auto mx-4 mb-4 bg-[#1c1c1e] rounded-3xl px-4 pt-4 pb-6">
              {/* Small items — 4 per row (Typography + Interactive) */}
              {filterItems(MOBILE_SMALL_ITEMS).length > 0 && (
                <div className="mb-4">
                  <div className="grid grid-cols-4 gap-3">
                    {filterItems(MOBILE_SMALL_ITEMS).map((item) => {
                      const Icon = item.icon
                      return (
                        <button
                          key={item.type}
                          onClick={() => { addMobileElement(item); setMobilePanelOpen(null) }}
                          className="aspect-square rounded-2xl bg-[#2c2c2e] flex flex-col items-center justify-center gap-1 active:scale-95 transition-transform"
                        >
                          <Icon className="h-5 w-5 text-[#8e8e93]" />
                          <span className="text-[9px] text-[#8e8e93] font-medium leading-tight text-center px-1">
                            {item.label}
                          </span>
                        </button>
                      )
                    })}
                  </div>
                </div>
              )}

              {/* Medium items — 3 per row (Layout + Media) */}
              {filterItems(MOBILE_MEDIUM_ITEMS).length > 0 && (
                <div className="mb-4">
                  <div className="grid grid-cols-3 gap-3">
                    {filterItems(MOBILE_MEDIUM_ITEMS).map((item) => {
                      const Icon = item.icon
                      return (
                        <button
                          key={item.type}
                          onClick={() => { addMobileElement(item); setMobilePanelOpen(null) }}
                          className="h-16 rounded-2xl bg-[#2c2c2e] flex flex-col items-center justify-center gap-1.5 active:scale-95 transition-transform"
                        >
                          <Icon className="h-5 w-5 text-[#8e8e93]" />
                          <span className="text-[9px] text-[#8e8e93] font-medium">{item.label}</span>
                        </button>
                      )
                    })}
                  </div>
                </div>
              )}

              {/* Circle items — Structural + Decorative */}
              {filterItems(MOBILE_CIRCLE_ITEMS).length > 0 && (
                <div className="flex flex-wrap justify-center gap-3">
                  {filterItems(MOBILE_CIRCLE_ITEMS).map((item) => {
                    const Icon = item.icon
                    return (
                      <button
                        key={item.type}
                        onClick={() => { addMobileElement(item); setMobilePanelOpen(null) }}
                        className="h-14 w-14 rounded-full bg-[#2c2c2e] flex flex-col items-center justify-center gap-0.5 active:scale-95 transition-transform"
                      >
                        <Icon className="h-5 w-5 text-[#8e8e93]" />
                        <span className="text-[8px] text-[#8e8e93] font-medium">{item.label}</span>
                      </button>
                    )
                  })}
                </div>
              )}

              {/* Empty state */}
              {filterItems(MOBILE_SMALL_ITEMS).length === 0 &&
                filterItems(MOBILE_MEDIUM_ITEMS).length === 0 &&
                filterItems(MOBILE_CIRCLE_ITEMS).length === 0 && (
                <div className="flex flex-col items-center justify-center py-16 text-center">
                  <p className="text-sm text-[#8e8e93]">No elements found</p>
                </div>
              )}
            </div>
          </div>
        )}
      </div>

      {/* ══════════════════════════════════════════════════════════════════════
          DESKTOP LAYOUT  (hidden on mobile, shown md and above)
      ══════════════════════════════════════════════════════════════════════ */}
      <div className="hidden md:flex md:flex-col md:flex-1 md:overflow-hidden">

      {/* ── Toolbar ─────────────────────────────────────────────────────────── */}
      <header className="h-14 border-b border-border flex items-center px-3 gap-2 shrink-0 bg-background z-30">
        {/* Left group */}
        <div className="flex items-center gap-2 mr-2">
          <Button
            variant="ghost"
            size="icon"
            className="h-8 w-8"
            onClick={() => setShowSidebar((s) => !s)}
            title={showSidebar ? "Hide elements" : "Show elements"}
          >
            {showSidebar ? <PanelLeftClose className="h-4 w-4" /> : <PanelLeftOpen className="h-4 w-4" />}
          </Button>

          <div className="h-5 w-px bg-border" />

          {/* Page selector */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" size="sm" className="h-8 gap-1.5 max-w-[160px]">
                <span className="truncate text-sm font-medium">{currentPage?.name ?? "Select Page"}</span>
                <ChevronDown className="h-3.5 w-3.5 shrink-0" />
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="start" className="w-52">
              {project.pageOrder.map((pageId) => {
                const page = project.pages[pageId]
                return (
                  <DropdownMenuItem
                    key={pageId}
                    onClick={() => setCurrentPage(pageId)}
                    className={cn(
                      "gap-2",
                      pageId === currentPageId && "bg-accent font-medium",
                    )}
                  >
                    <span className="flex-1 truncate">{page.name}</span>
                    <span className="text-[10px] text-muted-foreground font-mono">{page.slug}</span>
                    {project.pageOrder.length > 1 && (
                      <button
                        onClick={(e) => {
                          e.stopPropagation()
                          deletePage(pageId)
                        }}
                        className="ml-1 text-muted-foreground hover:text-destructive transition-colors"
                        title="Delete page"
                      >
                        <Trash2 className="h-3 w-3" />
                      </button>
                    )}
                  </DropdownMenuItem>
                )
              })}
              <DropdownMenuSeparator />
              <DropdownMenuItem onClick={() => setAddPageOpen(true)}>
                <Plus className="h-3.5 w-3.5 mr-2" />
                Add Page
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>
        </div>

        {/* Center group — view & device toggles */}
        <div className="flex items-center gap-1.5 mr-auto">
          {/* View mode */}
          <div className="flex items-center bg-muted rounded-md p-0.5">
            <button
              onClick={() => setViewMode("builder")}
              className={cn(
                "flex items-center gap-1.5 px-2.5 py-1 text-xs rounded transition-all",
                viewMode === "builder"
                  ? "bg-background text-foreground shadow-sm font-medium"
                  : "text-muted-foreground hover:text-foreground",
              )}
            >
              <Pencil className="h-3 w-3" />
              Builder
            </button>
            <button
              onClick={() => setViewMode("flow")}
              className={cn(
                "flex items-center gap-1.5 px-2.5 py-1 text-xs rounded transition-all",
                viewMode === "flow"
                  ? "bg-background text-foreground shadow-sm font-medium"
                  : "text-muted-foreground hover:text-foreground",
              )}
            >
              <GitBranch className="h-3 w-3" />
              Flow
            </button>
          </div>

          {/* Device width (only in builder mode) */}
          {viewMode === "builder" && (
            <div className="flex items-center bg-muted rounded-md p-0.5">
              {(
                [
                  { id: "desktop", icon: Monitor },
                  { id: "tablet", icon: Tablet },
                  { id: "mobile", icon: Smartphone },
                ] as { id: DeviceWidth; icon: typeof Monitor }[]
              ).map(({ id, icon: Icon }) => (
                <button
                  key={id}
                  onClick={() => setDeviceWidth(id)}
                  title={id}
                  className={cn(
                    "p-1.5 rounded transition-all",
                    deviceWidth === id
                      ? "bg-background text-foreground shadow-sm"
                      : "text-muted-foreground hover:text-foreground",
                  )}
                >
                  <Icon className="h-3.5 w-3.5" />
                </button>
              ))}
            </div>
          )}
        </div>

        {/* Right group */}
        <div className="flex items-center gap-1.5">
          {/* Undo / Redo */}
          <Button
            variant="ghost"
            size="icon"
            className="h-8 w-8"
            onClick={undo}
            disabled={!canUndo}
            title="Undo"
          >
            <Undo2 className="h-4 w-4" />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            className="h-8 w-8"
            onClick={redo}
            disabled={!canRedo}
            title="Redo"
          >
            <Redo2 className="h-4 w-4" />
          </Button>

          <div className="h-5 w-px bg-border" />

          <Button
            variant="ghost"
            size="sm"
            className="h-8 gap-1.5"
            onClick={() => setThemeOpen(true)}
            title="Theme settings"
          >
            <Eye className="h-3.5 w-3.5" />
            Theme
          </Button>

          <Button
            variant="ghost"
            size="sm"
            className="h-8 gap-1.5"
            onClick={() => setExportOpen(true)}
            title="Export project"
          >
            <Download className="h-3.5 w-3.5" />
            Export
          </Button>

          {onSave && (
            <Button
              size="sm"
              className="h-8 gap-1.5"
              onClick={handleSave}
              disabled={isSaving}
            >
              <Save className="h-3.5 w-3.5" />
              {isSaving ? "Saving..." : "Save"}
            </Button>
          )}

          <div className="h-5 w-px bg-border" />

          <Button
            variant="ghost"
            size="icon"
            className="h-8 w-8"
            onClick={() => setShowProperties((s) => !s)}
            title={showProperties ? "Hide properties" : "Show properties"}
          >
            {showProperties ? (
              <PanelRightClose className="h-4 w-4" />
            ) : (
              <PanelRightOpen className="h-4 w-4" />
            )}
          </Button>
        </div>
      </header>

      {/* ── Main area ───────────────────────────────────────────────────────── */}
      {viewMode === "builder" ? (
        <DndContext
          sensors={sensors}
          onDragStart={handleDragStart}
          onDragEnd={handleDragEnd}
        >
          <div className="flex flex-1 overflow-hidden">
            {showSidebar && <BuilderSidebar />}
            <BuilderCanvas deviceWidth={deviceWidth} />
            {showProperties && selectedElementId && <PropertiesPanel />}
          </div>

          <DragOverlay>
            {activeDragId ? (
              <div className="bg-indigo-600 text-white text-xs font-medium px-3 py-1.5 rounded-lg shadow-xl opacity-90 pointer-events-none">
                Moving element...
              </div>
            ) : null}
          </DragOverlay>
        </DndContext>
      ) : (
        <div className="flex-1 overflow-hidden">
          <PageFlow />
        </div>
      )}

      </div>{/* end desktop layout */}

      {/* ── Dialogs (shared between mobile and desktop) ──────────────────────── */}
      <AddPageDialog open={addPageOpen} onClose={() => setAddPageOpen(false)} />
      <ExportDialog open={exportOpen} onClose={() => setExportOpen(false)} />
      <ThemePanel open={themeOpen} onClose={() => setThemeOpen(false)} />
    </div>
  )
}
